version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: mople-db
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DBNAME}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mople-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mople/app:latest
    container_name: mople-app
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mople-network

  ws-service:
    image: ws-service:latest
    container_name: ws-service
    build:
      context: ./ws-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - SPRING_PROFILES_ACTIVE=ws
    ports:
      - "8081:8081"
    networks:
      - mople-net
    depends_on:
      - redis

  sse-service:
    image: sse-service:latest
    container_name: sse-service
    build:
      context: ./sse-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - SPRING_PROFILES_ACTIVE=sse
    ports:
      - "8082:8082"
    networks:
      - mople-net
    depends_on:
      - redis

  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mople-app
      - ws-service
      - sse-service
    networks:
      - mople-net


volumes:
  postgres-data:
networks:
  mople-network:
    driver: bridge

