version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: mople-db
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DBNAME}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "6543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mople-network
volumes:
  postgres-data:
networks:
  mople-network:
    driver: bridge