server:
  port: 80
  ssl:
    enabled: false

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    from: sbmople22@example.com
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 30000
      mail.smtp.writetimeout: 5000
jwt:
  secret: ${SPRING_JWT_SECRET}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health