spring:
  application:
    name: mople
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  profiles:
    active:
      - dev
logging:
  level:
    org.springframework.core.env: DEBUG
    org.springframework.boot.context.config: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
    org.springframework.jdbc.datasource: DEBUG