server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mople
    username: mople_user
    password: mople_1234
  jpa:
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: test_jwt_secret_1234567890_test_jwt_secret_1234567890