server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/mople
    username: mople_user
    password: mople_1234
  jpa:
    properties:
      hibernate:
        format_sql: true