name: Test and Coverage

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Write .env file
        run: |
          cat <<EOF > .env
          ${{ secrets.ENV_FILE }}
          EOF
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Apply schema.sql to PostgreSQL
        run: |
          psql -h localhost -p 5432 -U mople_user -d mople -f src/main/resources/schema.sql
        env:
          PGPASSWORD: mople_1234

      - name: Run tests and generate coverage
        run: ./gradlew clean test jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: codecov-coverage
